# name: Continuous Integration-hello DevOps

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   build-and-push:
#     runs-on: ["self-hosted", "Linux X64", "hellodevops"]

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     # - name: Log in to GitHub Container Registry
#     #   run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#     - name: Stop Existing Container
#         run: |
#           docker compose down || true

#     - name: Build and Run Container
#         run: |
#           docker compose up -d --build